plugins:
  awesomeness_enabled:
    default: true
    client: true
  awesomeness_max_volume:
    default: 10
    client: true
  openid_connect_enabled:
    default: false
  openid_connect_discovery_document:
    default: ""
  openid_connect_client_id:
    default: ""
  openid_connect_client_secret:
    default: ""
  openid_connect_allow_association_change:
    default: false
  openid_connect_authorize_scope:
    default: "openid"
  openid_connect_verbose_logging:
    default: false
  openid_connect_token_scope:
    default: ""
  openid_connect_error_redirects:
    default: ''
    type: list
    list_type: secret
required:
  title:
    client: true
    default: "Amnimo"
  site_description:
    default: "IOT community portal forum"
  contact_email:
    client: true
    default: "muthukkumar@nichesoft.net"
    type: email
  site_contact_username:
    default: "system"
    type: username
  company_name:
    default: "Amnimo"
  governing_law:
    default: "Japan"
  city_for_disputes:
    default: "Tokyo"
